# Generated by Django 4.2.1 on 2023-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="a", max_length=20),
            preserve_default=False,
        ),
    ]
