# Generated by Django 4.2.1 on 2023-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player", name="name", field=models.CharField(max_length=30),
        ),
    ]
