# Generated by Django 4.2.1 on 2023-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="badge",
            field=models.ImageField(null=True, upload_to="badges/"),
        ),
    ]
