# Generated by Django 4.2.1 on 2023-05-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_badge"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="badge",),
    ]
