# Generated by Django 4.2.1 on 2023-05-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_remove_team_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="position",
            field=models.CharField(default="Atacante", max_length=15),
            preserve_default=False,
        ),
    ]
