# Generated by Django 4.2.1 on 2023-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_player_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team", name="name", field=models.CharField(max_length=30),
        ),
    ]
