# Generated by Django 4.2.1 on 2023-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_team_image_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("image_name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
