# Generated by Django 4.2.1 on 2023-05-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_delete_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="goals_scored",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player", name="saves", field=models.IntegerField(null=True),
        ),
    ]
