# Generated by Django 4.2.1 on 2023-05-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_rename_goals_scored_player_scored_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="assists", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="player",
            name="saves",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
