# Generated by Django 4.2.1 on 2023-05-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_player_assists_alter_player_saves"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="times_mvp", field=models.IntegerField(default=0),
        ),
    ]
