# Generated by Django 4.2.1 on 2023-05-28 11:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_player_times_mvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="exact_positions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3), default=[""], size=8
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="fifa_rating",
            field=models.IntegerField(default=0),
        ),
    ]
