# Generated by Django 4.2.1 on 2023-05-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_player_exact_positions_player_fifa_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPlayer",
            fields=[
                (
                    "player_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="teams.player",
                    ),
                ),
                ("nacionality", models.CharField(max_length=20)),
                ("foot", models.CharField(max_length=10)),
                ("weight", models.IntegerField()),
                ("height", models.FloatField()),
                ("dribbling_stat_min", models.IntegerField()),
                ("shooting_stat_min", models.IntegerField()),
                ("passing_stat_min", models.IntegerField()),
                ("physical_stat_min", models.IntegerField()),
                ("defense_stat_min", models.IntegerField()),
                ("tackle_stat_min", models.IntegerField()),
                ("steal_stat_min", models.IntegerField()),
                ("speed_stat_min", models.IntegerField()),
                ("dribbling_stat_max", models.IntegerField()),
                ("shooting_stat_max", models.IntegerField()),
                ("passing_stat_max", models.IntegerField()),
                ("physical_stat_max", models.IntegerField()),
                ("defense_stat_max", models.IntegerField()),
                ("tackle_stat_max", models.IntegerField()),
                ("steal_stat_max", models.IntegerField()),
            ],
            bases=("teams.player",),
        ),
        migrations.CreateModel(
            name="MarketKeeper",
            fields=[
                (
                    "marketplayer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="teams.marketplayer",
                    ),
                ),
                ("e_stat_min", models.IntegerField()),
                ("r_stat_min", models.IntegerField()),
                ("pa_stat_min", models.IntegerField()),
                ("s_stat_min", models.IntegerField()),
                ("po_stat_min", models.IntegerField()),
                ("v_stat_min", models.IntegerField()),
                ("e_stat_max", models.IntegerField()),
                ("r_stat_max", models.IntegerField()),
                ("pa_stat_max", models.IntegerField()),
                ("s_stat_max", models.IntegerField()),
                ("po_stat_max", models.IntegerField()),
                ("v_stat_max", models.IntegerField()),
            ],
            bases=("teams.marketplayer",),
        ),
    ]
