# Generated by Django 4.2.1 on 2023-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0019_marketplayer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="clausule", field=models.IntegerField(default=0),
        ),
    ]
